# Generated by Django 4.1.7 on 2023-03-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scannedsupplier',
            old_name='logo_path',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='new_supplier',
        ),
    ]
